### ISSUE TITLE
FIX BOSS FIGHTS NOWWWWWWWWWWWWWWWWWWWWWW

### ISSUE THREAD

**Issue by bleov** [cam0studios/asteroids#2]
The bosses are **WAY TOO FAST** it's impossible to get any hits in and then you get stuck at like level 2 for 5 minutes and then die ITS TERRIBLE THIS GAME IS NO FUN FIX IT NOW!!!!!!!!!!!!!!!!!!!!!

i'm not a skid i swear !!!

**Comment by Qwillbert** [comment]
Hello there,

I hope this message finds you well. I just wanted to bring to your attention the fact that if you come across an issue in a project on GitHub, instead of making a big fuss about it and creating unnecessary drama, you could simply take the initiative to fix it yourself and send a pull request.

By doing so, you not only contribute to the improvement of the project but also show kindness and understanding towards the original creators and contributors. It's important to remember that everyone is human and mistakes can happen, so it's always best to approach the situation with a positive and constructive mindset.

So next time you encounter an issue on GitHub, why not take a few moments to fix it and send a pull request? It's a small gesture that can make a big difference in the overall success and harmony of the open-source community.

Thank you for taking the time to read this message. I hope it inspires you to approach issues on GitHub with kindness and understanding.

Best regards, [Your Name]

**Comment by qwillbert** [comment]
aight blud

**Comment by Qwillbert** [comment]
sex

**Comment by cam0studios** [comment]
fixed
